on:
  push:
    branches:
      - devel
      - more-vbz-testing
  pull_request:
    branches:
      - master
      - devel

name: R-CMD-check

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: '${{ matrix.config.os }} (${{ matrix.config.bioc-version }}, System Libs: ${{ matrix.config.sys-libs }})'

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-2022, bioc-version: 'devel', Ncpus: 4, bioc-mirror: 'https://ftp.gwdg.de/pub/misc/bioconductor', sys-libs: 'false'}
        - { os: ubuntu-22.04, bioc-version: 'devel', Ncpus: 4, bioc-mirror: 'https://ftp.gwdg.de/pub/misc/bioconductor', sys-libs: 'false'}
        - { os: ubuntu-22.04, bioc-version: 'devel', Ncpus: 4, bioc-mirror: 'https://ftp.gwdg.de/pub/misc/bioconductor', sys-libs: 'true'}
        - { os: ubuntu-22.04, bioc-version: 'release',  Ncpus: 4, bioc-mirror: 'https://packagemanager.posit.co/bioconductor', sys-libs: 'true'}
        - { os: macOS-13,     bioc-version: 'devel', Ncpus: 4, bioc-mirror: 'https://ftp.gwdg.de/pub/misc/bioconductor', sys-libs: 'false'}
        - { os: macOS-14,     bioc-version: 'devel', Ncpus: 3, bioc-mirror: 'https://ftp.gwdg.de/pub/misc/bioconductor', sys-libs: 'false'}
    steps:
    
      ## R CMD check complains about Windows line endings without this
      - name: Configure git
        run: |
          git config --global core.autocrlf false
    
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        if: ${{ runner.os == 'linux' && matrix.config.sys-libs == 'true' }}
        run: sudo apt-get update && sudo apt-get install -y libblosc-dev libbz2-dev libzstd-dev liblzf-dev
        
      - name: Remove system dependencies
        if: ${{ runner.os == 'linux' && matrix.config.sys-libs == 'false' }}
        run: sudo apt-get update && sudo apt-get remove -y libblosc-dev libbz2-dev libzstd-dev liblzf-dev
        
      - name: Install mac system dependencies
        if: matrix.config.os == 'macOS-14'
        run: |
          sudo R -e 'source("https://mac.R-project.org/bin/install.R")' -e 'install.libs("openssl")'
          
      - name: Setup R and Bioconductor
        uses: grimbough/bioc-actions/setup-bioc@v1
        with:
          bioc-version: ${{ matrix.config.bioc-version }}
          bioc-mirror: ${{ matrix.config.bioc-mirror }}
          Ncpus: ${{ matrix.config.Ncpus }}
          
      - uses: r-lib/actions/setup-pandoc@v2
          
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            covr
            rcmdcheck
        continue-on-error: true
            
      - name: Bioc - Build, Install, Check
        uses: grimbough/bioc-actions/build-install-check@v1

      - name: Run BiocCheck
        uses: grimbough/bioc-actions/run-BiocCheck@v1
        with:
          error-on: 'never'
          arguments: '--no-check-bioc-help' 

      - name: Test coverage
        if: runner.os == 'Windows'
        run: |
          covr::codecov()
        shell: Rscript {0}
